### ISSUE TITLE
height and width Constraints not working

### ISSUE THREAD

**Issue by pprevalon** [efremidze/VisualEffectView#12]
`let effect = VisualEffectView()//VisualEffectView(frame: CGRect(x: 0, y: 0, width: 600, height: 600))
        effect.translatesAutoresizingMaskIntoConstraints = false
        effect.colorTint = .red
        effect.colorTintAlpha = 0.2
        effect.blurRadius = 10
        effect.scale = 1

        view.addSubview(effect)
        effect.heightAnchor.constraint(equalTo: view.heightAnchor, multiplier: 0).isActive = true
        effect.widthAnchor.constraint(equalTo: view.widthAnchor, multiplier: 0).isActive = true
`

**Comment by efremidze** [comment]
Your missing `NSLayoutConstraint.activate()`.
```
NSLayoutConstraint.activate([effect.heightAnchor.constraint(equalTo: view.heightAnchor)])
```

**Comment by efremidze** [comment]
This is an auto layout question. Not related to this library. Your missing constraints.
