### ISSUE TITLE
iOS 8.x crash

### ISSUE THREAD

**Issue by Kofktu** [efremidze/VisualEffectView#14]
Hello, 

I'm using VisualEffectView to find a custom UIVisualEffectView.
When I read ReadMe, iOS 8.0 + is actually crashing when iOS 8.x is run.

```
private let blurEffect = (NSClassFromString("_UICustomBlurEffect") as! UIBlurEffect.Type).init()
```

fatal error: unexpectedly found nil while unwrapping an Optional value

it's probably an iOS9+ API

**Comment by efremidze** [comment]
I haven't tested on iOS 8 in a while. I can update it to iOS 9 and above.
