### ISSUE TITLE
Screen is shivering when i added this in tableview with multiple cell.Please suggest how can i fix it?

### ISSUE THREAD

**Issue by iAmita** [efremidze/VisualEffectView#20]
### New Issue Checklist

- [x] I updated VisualEffectView to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/efremidze/VisualEffectView/blob/master/.github/CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/efremidze/VisualEffectView).
- [x] I searched for [existing GitHub issues](https://github.com/efremidze/VisualEffectView/issues).

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by efremidze** [comment]
What are you adding the VisualEffectView to?
