### ISSUE TITLE
cannot support iOS 14

### ISSUE THREAD

**Issue by azureplus** [efremidze/VisualEffectView#23]
cannot support iOS 14

**Comment by efremidze** [comment]
can you elaborate?

**Comment by alireza12t** [comment]
In ios 13 and earlier it looks like this 
![image](https://user-images.githubusercontent.com/31301632/85922829-6c9ea780-b89b-11ea-9be4-fe4a2e5e0090.png)
But in iOS 14 its like this :
![image](https://user-images.githubusercontent.com/31301632/85922868-8b9d3980-b89b-11ea-81bd-ba857f9d4664.jpeg)

**Comment by zhoulijun12315** [comment]
yes，i have the same problem。

**Comment by efremidze** [comment]
Thanks for explaining, needs investigation.

**Comment by alireza12t** [comment]
Thanks

**Comment by zporges** [comment]
Same in my app - blurring is broken in iOS 14

**Comment by LieonShelly** [comment]
same problem

**Comment by R0uter** [comment]
same here 😂

**Comment by AssyriaGameStudio** [comment]
Yep, same problem here - any update?

**Comment by lowlabs** [comment]
The UIImage+ImageEffects extension provided by Apple (which creates a UIImage replicating UIBlurEffect) is also broken under iOS14. Same result: monochrome and no blur.

**Comment by zporges** [comment]
Luckily SwiftUI lets you specify a blur radius - no private api required. So I plan to stop using this framework, and instead just wrap a SwiftUI view with a blur effect for iOS 13/14 users.

**Comment by fthdgn** [comment]
@zporges Can you share a snippet code or documentation page for how to specify blur radius on SwiftUI?

**Comment by lowlabs** [comment]
@zporges Next to blur I also need to darken and saturatize the view. If the saturation(amount:) modifier in SwiftUI handles values bigger than 1 this may work. I also need to animate the blurradius. Not so familiar with SwiftUI so I'll need to do some experimenting.

**Comment by zporges** [comment]
> @zporges Can you share a snippet code or documentation page for how to specify blur radius on SwiftUI?

It's as simple as:
```
ViewToBlur()
    .blur(radius: 20)
```

https://developer.apple.com/documentation/swiftui/view/blur(radius:opaque:)

**Comment by AssyriaGameStudio** [comment]
SwiftUI is an alternative; however only 81% of iOS devices that are currently active are running iOS 13, so there's still nearly 20% of the market for which SwiftUI isn't a viable option assuming you're trying to reach as much of the iOS market as possible.

**Comment by zporges** [comment]
You could conditionally do a SwiftUI Blur on iOS 13+ and a VisualEffectView on iOS 12 and earlier though

**Comment by AssyriaGameStudio** [comment]
Yeah fair; though I'm struggling to get SwiftUI blurring contents behind the SwiftUI view in the same manner that the VisualEffectView does?

**Comment by efremidze** [comment]
Hopefully Apple fixes the UIVisualEffectView bugs

**Comment by mmdock** [comment]
I'm a little confused as to why this is being considered an Apple bug? The default UIVisualEffectView is still working as expected when used, it is just this framework not working.  Thankfully for my needs I can temporarily use the default, it just won't look as.... nice.

**Comment by gsbernstein** [comment]
If you know how to get it working, please make a PR!

**Comment by mmdock** [comment]
lol I'm not smart enough to know why UIVisualEffectView is working and this framework isn't (even though VisualEffectView is a subclass of UIVisualEffectView) in my project at least.  That's why I was asking about why this is being considered an apple bug, I was curious so as to learn.  I read the thread above but i didn't really follow it

**Comment by efremidze** [comment]
Currently researching a proper solution. Will keep everyone posted.

**Comment by fthdgn** [comment]
@mmdock VisualEffectView uses a private/hidden class named __UICustomBlurEffect_ instead of the default _UIBlurEffect_, because __UICustomBlurEffect_ has properties to manage blur radius. __UICustomBlurEffect_ is written by Apple but it is not part of public API. The implementation of  __UICustomBlurEffect_ is changed on iOS 14 and it no longer works. It is not Apple's bug, but it is caused by Apple. We were taking this risk by using private API.

**Comment by unboxme** [comment]
Same problem. 

But I If found a good idea here: https://stackoverflow.com/a/55378168/3449400
Just use `UIVisualEffectView.alpha` for animation and `UIVisualEffectView.fractionComplete` to set blur intensity.

Yes, it isn't like a "real blur" animation, but it is still smooth, non resource-intensive and blurs in a real time.

**Comment by zolobdz** [comment]
Thanks @unboxme 
According to your clue, I write this class to replace this function

```

import UIKit

class GPCVisualEffectView: UIVisualEffectView{
    private lazy var blurAnimator = UIViewPropertyAnimator(duration: 0.5, curve: .linear, animations: nil)
    
    init() {
        super.init(effect: nil)
        configAnimator()
    }
    
    init( frame: CGRect) {
        super.init(effect: nil)
        self.frame = frame
        configAnimator()
    }
    
    override init(effect: UIVisualEffect?) {
        super.init(effect: nil)
        configAnimator()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        configAnimator()
    }
    
    private func configAnimator() {
        effect = nil
        autoresizingMask = [.flexibleHeight, .flexibleWidth]
        blurAnimator.addAnimations {
            self.effect = UIBlurEffect(style: .light)
        }
        blurAnimator.fractionComplete = 0.07
    }

}


```

usage
```
let overlay = GPCVisualEffectView()
overlay.frame = xxx
view.addSubview(overlay)
```

**Comment by HanSJin** [comment]
Is there a Genius to fix this?

**Comment by Maxim-Zakopaylov** [comment]
@zolobdz thank you for your code. But I have a question. What about custom colorTint? Because it's only one reason what I use this library.

**Comment by cuzv** [comment]
@unboxme @zolobdz `UIViewPropertyAnimator` workaround has another problem remain unresolved: https://github.com/fichek/AnimateBlurRadius/issues/1

**Comment by zolobdz** [comment]
@Maxim-Zakopaylov Hi, you can set UIVisualEffect.backgroundColor in `addAnimations` closure, but don't forget to set color alpha. I hope this will help.
`
blurAnimator.addAnimations {
     self.effect = UIBlurEffect(style: .light)
     self.backgroundColor = UIColor.blue.withAlphaComponent(0.2)
}
`

**Comment by zolobdz** [comment]
@cuzv Thank you for reminding. Yes, this issue still exists. the workaround i provide is just suitable for settled blur-alpha. I will update my comment.

**Comment by perfectdim** [comment]
Hello! I've made a solution. https://github.com/perfectdim/CustomBlurEffectView
IOS 13- version is based on this repo, and IOS 14+ is temporary working solution.

**Comment by HanSJin** [comment]
@perfectdim Your repo? not PR? kkk

**Comment by perfectdim** [comment]
> @perfectdim Your repo? not PR? kkk

I'm sorry, what you mean? =)

**Comment by HanSJin** [comment]
@perfectdim Thanks for your solution :) 
but I am not sure whether to use this `VisualEffectView` or your NEW `CustomBlurEffectView` repository.
Because I don't know if your repository will be updated in the future. 
Anyway, your solution works well 👍🏻

**Comment by perfectdim** [comment]
@HanSJin I will use my solution on my project, so I hope I will update it if needed =)
If guys from `VisualEffectView` will check my solution and integrate it to their module it will be ok for me =)

**Comment by unboxme** [comment]
Hey guys! After a couple days of research I found another solution without modifying `UIBlurEffect` directly. So I added a my vision of blurring implementation [[here]](https://github.com/unboxme/Blurberry).

Current version works only on iOS 13+, but next week I planned to add iOS 10+ support (I suppose it will based on `UIBlurEffect`). 

Feel free to use my approach anywhere.

**Comment by efremidze** [comment]
@unboxme Your solution appears to work. I can update VisualEffectView to use the same approach for iOS 13+.

**Comment by gsbernstein** [comment]
Thank you!!!

**Comment by nadimalam** [comment]
Hey guys, was wondering if any of you could potentially help me please as ive been stuck on this issue for a while.

I cant seem the blur effect to work on iOS14 devices, it works fine on iOS13 though.

```
    let blurEffect = (NSClassFromString("_UICustomBlurEffect") as! UIBlurEffect.Type).init()
    blurEffect.setValue(8, forKeyPath: "blurRadius")
    blurView = UIVisualEffectView(effect: blurEffect)
    blurView.frame = UIScreen.main.bounds
    blurView.alpha = 1
    view.insertSubview(blurView, aboveSubview: imvBackground)
```

Is anyone please able to help me fix this? Thanks.
