### ISSUE TITLE
Some problem with saturation

### ISSUE THREAD

**Issue by MrGrig** [efremidze/VisualEffectView#29]
### New Issue Checklist

- [ x] I updated VisualEffectView to the latest version.
- [ x] I read the [Contribution Guidelines](https://github.com/efremidze/VisualEffectView/blob/master/.github/CONTRIBUTING.md).
- [x ] I read the [documentation](https://github.com/efremidze/VisualEffectView).
- [ x] I searched for [existing GitHub issues](https://github.com/efremidze/VisualEffectView/issues).

### Issue Description
I'm use:
blurRadius = 5
colorTintAlpha = nil (or .clear)
scale = 1

result:
![](https://i.ibb.co/6YYqDf0/photo-2020-09-24-17-47-44.jpg)

### Environment

- **iOS Version**: 14.0
- **Device(s)**: iPhone 10 XMax

**Comment by MrGrig** [comment]
on iOS below 14 all OK

**Comment by Montana2313** [comment]
Same problem

**Comment by shonalien** [comment]
Same problem, and nothing helps. @mkeshnoda can you please help us?

**Comment by shonalien** [comment]
Maybe https://github.com/efremidze/VisualEffectView/issues/28 is the same problem?

**Comment by K0ngo** [comment]
Same problem. It's broken on ios14

**Comment by LucyJeong** [comment]
same problem :(

**Comment by ziv-mishloha** [comment]
+1

**Comment by Ogerets** [comment]
@efremidze So why this is closed?
