### ISSUE TITLE
completely broke my xcodeproject, i had to refresh and pull from git.

### ISSUE THREAD

**Issue by coratype** [efremidze/VisualEffectView#46]
iOS 18, Mac OS Sequoia Version 15.0 Beta (24A5320a)

im not sure if its the beta, or if its the package. but every single time i tried to remove the package from the dependencies, it would crash my Xcode. also, there were a bunch of warning about Color being only available on iOS 13.0.

**Comment by efremidze** [comment]
Are you using SPM?

**Comment by coratype** [comment]
yes

**Comment by foxfollow** [comment]
same issue macOS: 15.0; xcode Version 16.0, iOS 17 (chaging of iOS doesn't help), use SPM
downgrade of [VisualEffectView](https://github.com/efremidze/VisualEffectView) to 4.1.5 fixes the issues

**Comment by efremidze** [comment]
Thank you, ill investigate today

**Comment by efremidze** [comment]
Fixed by #47
