### ISSUE TITLE
What is the scale factor?

### ISSUE THREAD

**Issue by mxcl** [efremidze/VisualEffectView#8]
If you answer I will submit a PR updating the docs. Thanks!

**Comment by efremidze** [comment]
I just tested it and it seems to make no difference unless u set it to 0. I'm thinking of removing it.

**Comment by k06a** [comment]
Maybe `[UIScreen mainScreen].scale` gives difference on 0.01 radius.

**Comment by mxcl** [comment]
Probably should leave it if we don't know what it does, but ensure it defaults to 1 so people don't wonder why the view isn't working.

**Comment by efremidze** [comment]
addressed in #11
